package com.skyautoplayer.storage

import com.skyautoplayer.importer.ImportResult
import com.skyautoplayer.importer.SkyJsonImporter
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Regression tests for the bundled song library.
 *
 * Reads `src/main/assets/bundled_sheets` straight off the filesystem (Gradle's
 * unit-test CWD is the module directory) instead of copying 24 MB into
 * `src/test/resources`. Generated by `tools/bundle_from_device_library.py`
 * (707 songs, taken from the device library).
 */
class BundledSheetsTest {

    private val dir = File("src/main/assets/bundled_sheets")
    private val expectedCount = 707

    /** W27: the runtime keeps no length rule; the script does the screening. */
    private val minDurationUs = BundledSheetSeeder.MIN_BUNDLED_DURATION_US

    private fun sheets(): List<File> {
        assertTrue(dir.isDirectory, "missing assets dir: ${dir.absolutePath}")
        return dir.listFiles { f -> f.isFile && f.extension == "txt" }!!.sortedBy { it.name }
    }

    @Test
    fun libraryShipsExactlyTheExpectedNumberOfSheets() {
        val files = sheets()
        assertEquals(
            expectedCount,
            files.size,
            "bundled sheet count changed; if intentional update expectedCount " +
                "AND tools/bundle_from_device_library.py (dir=${dir.absolutePath})"
        )
    }

    @Test
    fun fileNameRulesAreSatisfied() {
        val files = sheets()
        val illegal = Regex("""[\\/:*?"<>|\u0000-\u001f]""")
        val problems = mutableListOf<String>()
        files.forEach { f ->
            if (illegal.containsMatchIn(f.name)) problems += "illegal char: ${f.name}"
            if (f.name.endsWith(".") || f.name.endsWith(" ")) problems += "trailing dot/space: ${f.name}"
        }
        val duplicates = files.groupBy { it.name.lowercase() }.filter { it.value.size > 1 }.keys
        assertTrue(duplicates.isEmpty(), "duplicate asset names: $duplicates")
        assertTrue(problems.isEmpty(), "bad asset names:\n" + problems.joinToString("\n"))
    }

    @Test
    fun everySheetImportsAndPassesTheDurationRule() {
        val importer = SkyJsonImporter()
        val failures = mutableListOf<String>()
        var totalEvents = 0L
        var totalNotes = 0L

        sheets().forEach { file ->
            val result = importer.import(file.name, file.readBytes())
            when (result) {
                is ImportResult.Failure ->
                    failures += "${file.name}: ${result.message}"
                is ImportResult.Success -> {
                    val timeline = result.timeline
                    if (timeline.events.isEmpty()) {
                        failures += "${file.name}: no events"
                    } else if (timeline.durationUs < minDurationUs) {
                        // The duration rule is enforced here as well as in the
                        // packaging script, so a bad rebuild fails the build.
                        failures += "${file.name}: duration ${timeline.durationUs}us < ${minDurationUs}us"
                    } else {
                        totalEvents += timeline.events.size
                        // `events.size` counts distinct timestamps (a chord is one
                        // event); the note total counts distinct (timestamp, key)
                        // pairs, which is what the device library reported.
                        totalNotes += timeline.events.sumOf { it.keys.size }
                    }
                }
            }
        }

        assertTrue(failures.isEmpty(), "${failures.size} sheet problem(s):\n" + failures.take(20).joinToString("\n"))
        // Device-library totals (W26): 341,522 events, which expand to 565,817
        // distinct (time, key) notes. Asserting both numbers catches a rebuild
        // that silently merges (chord folding) or drops notes.
        assertTrue(
            totalNotes in 564_800..566_800,
            "expected ~565,817 bundled notes, got $totalNotes (events=$totalEvents)"
        )
        assertTrue(
            totalEvents in 340_500..342_500,
            "expected ~341,522 chord events, got $totalEvents"
        )
    }

    @Test
    fun everyEventRespectsTheTimelineInvariants() {
        val importer = SkyJsonImporter()
        val failures = mutableListOf<String>()

        sheets().forEach { file ->
            val result = importer.import(file.name, file.readBytes())
            if (result !is ImportResult.Success) {
                failures += "${file.name}: import failed"
                return@forEach
            }
            val events = result.timeline.events
            if (events.any { it.keys.isEmpty() }) failures += "${file.name}: empty keys"
            if (events.any { e -> e.keys.any { it !in 0..14 } }) failures += "${file.name}: key out of 0..14"
            if (events.any { it.holdUs <= 0 }) failures += "${file.name}: non-positive hold"
            if (events.zipWithNext().any { (a, b) -> a.atUs > b.atUs }) failures += "${file.name}: not sorted"
            if (result.timeline.durationUs < 0) failures += "${file.name}: negative duration"
        }

        assertTrue(failures.isEmpty(), "${failures.size} invariant problem(s):\n" + failures.take(20).joinToString("\n"))
    }
}
